### ISSUE TITLE
JavaScript Standard Style on CI

### ISSUE THREAD

**Issue by joeljuca** [dsafio/challenges#2]
We need to lint challenges' source code during CI too.

See dsafio/dsafio#15.

**Comment by geymed** [comment]
@joelwallis I can take this one as well.

**Comment by joeljuca** [comment]
@geymed awesome! 🎉

Let's work on dsafio/dsafio#26 first, and get it merged. Since these two issues are very similar it would be a breeze for you to get it merged after the first one.
